apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yml
  - postgres.yml
  - ingress.yml
  - hpa.yml

images:
  - name: xilinx19/url-shortener
    newName: 586789648037.dkr.ecr.us-east-1.amazonaws.com/url-shortener
    newTag: v1
