apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yml
  - postgres.yml
  - ingress.yml
  - hpa.yml

images:
  - name: xilinx19/url-shortener
    newName: 347754356200.dkr.ecr.us-east-1.amazonaws.com/url-shortener
    newTag: af860d68f55ef6b6d871dd4f5dd32e274413952f
